### PR TITLE
Fix problem with issuer admins not seeing all badges

### LINKED ISSUE #216: Issuers don't see all their badges
In prod, I added myself as an issuer to "Self-paced Activities Curated by DYN" and "Chicago Botanic Garden". I only see badges from one program in "Self-paced Activities Curated by DYN" not all the programs.

/cc @threeqube

### PR DESCRIPTION
**Pull request by brianloveswords**
Fixes #216 

Ready for review

### CODE REVIEW

**Comment by brianloveswords** [comment]
Fixed, and with sorting!

img

**Comment by brianloveswords** [comment]
Commit 84e9a023d0b3a23842813740cc5e60ef78a58af1 contains the actual fix for the problem.

**Comment by brianloveswords** [comment]
@toolness or @cmcavoy can you review?

**Comment by threeqube** [comment]
With sorting?!?! Yay!!!! :+1:

File: lib/util.js [hunk 1]
```diff
@@ -168,9 +168,9 @@ util.deepProp = function () {
   };
 };
 
-util.objWrap = function objWrap(prop, obj) {
-  obj = obj || {};
+util.objWrap = function objWrap(prop) {
   return function (val) {
+    const obj = {};
     return (obj[prop] = val, obj);
```
Comment (toolness) [inline lib/util.js:174]: Just as a stylistic note ... even though it looks like this line isn't even part of the commit, the line took me a while to grok. Could just be me, but it'd be much easier to read if it were two separate statements, e.g.

``` javascript
obj[prop] = val;
return obj;
```

File: routes/badge.js [hunk 2]
```diff
@@ -375,29 +375,50 @@ exports.findById = function findById(req, res, next) {
...
+              (a.name || ''),
+            ].join(':');
+            const strB = [
+              (b.program.issuer.name || ''),
+              (b.program.name || ''),
+              (b.name || ''),
+            ].join(':');
+            return (strA).localeCompare(strB);
+          });
+
```
Comment (toolness) [inline routes/badge.js:421]: This is all spiffy but test cases for lines 406-420 in particular would both make the code easier to understand and more awesome. Would it be worth it to split this chunk off into a separate function taking a single `badges` argument, which would be nice and easy to test?

I realize we're under a supertight deadline though so it's ok if it can't be done.

**Comment by toolness** [comment]
Looks good to me!

**Comment by cmcavoy** [comment]
Thanks @toolness for the review..you're right, we're under a bit of a deadline, but I appreciate you reviewing. We'll get back to the review / revise / review pattern soon.

File: lib/util.js (hunk 1 above)
Comment (brianloveswords) [inline lib/util.js:174]: Yeah, definitely. I do this sometimes because I get mad that I can't do something like `return {[prop]: val}`, I _really_ want it to be a one liner. I also just really like using the comma operator, but it would for sure be clearer as two lines.

File: routes/badge.js (hunk 2 above)
Comment (brianloveswords) [inline routes/badge.js:421]: Definitely, I thought about splitting it out (and DRYing it out), but I was just trying to land it as quick as possible.

Comment (brianloveswords) [inline routes/badge.js:421]: Though I would rather split it out at 408, just the sort function itself taking `(badgeA, badgeB)` rather than something that takes a whole array of `badges`.
